blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/SRWieZ/nativephp-mobile-packages/discussions
    about: Please ask questions and discuss ideas in GitHub Discussions instead of opening an issue.
